server:
  port: 9000
---

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    version: "Booking app"

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:database/migration
#    ignore-migration-patterns: repeatable:missing

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true

  jwt:
    secretKey: ${JWT_SECRET}
    accessTokenExpiration: 604800 # 5 M
    refreshTokenExpiration: 604800 # 7 Day

stripe:
  secret_key: ${STRIPE_SANDBOX_SECRET_KEY}
  webhook_secret_key: ${STRIPE_WEBHOOK_SECRET_KEY}
  publishable_key: ${STRIPE_SANDBOX_PUBLISHABLE_KEY}